all:
  children:

    spine:
      hosts:
        spine1:
          ansible_host: 192.168.1.10

    leaf:
      hosts:
        leaf1:
          ansible_host: 192.168.1.11
        leaf2:
          ansible_host: 192.168.1.12

    border-leaf:
      hosts:
        border1:
          ansible_host: 192.168.1.13

  vars:
    ansible_user: admin
    ansible_password: admin
    ansible_connection: network_cli
